ALTER TABLE hub_match_player_stats
    ADD COLUMN IF NOT EXISTS free_kicks INT NOT NULL DEFAULT 0 AFTER goals_conceded,
    ADD COLUMN IF NOT EXISTS penalties INT NOT NULL DEFAULT 0 AFTER free_kicks,
    ADD COLUMN IF NOT EXISTS corners INT NOT NULL DEFAULT 0 AFTER penalties,
    ADD COLUMN IF NOT EXISTS throw_ins INT NOT NULL DEFAULT 0 AFTER corners,
    ADD COLUMN IF NOT EXISTS goal_kicks INT NOT NULL DEFAULT 0 AFTER throw_ins;
